language: c

services:
  - docker

before_install:
- docker pull centos:6
- docker run centos:6 /bin/sh -c "cat /proc/self/maps"
- docker build -t vsyscall-test:v1 .
- docker run vsyscall-test:v1 /bin/sh -c "/vsyscall-test"
