language: c

services:
  - docker

before_install:
- docker pull centos:6
- docker run centos:6 /bin/sh -c "gcc -o vsyscall-test vsyscall-test.c; ./vsyscall-test"
- docker run centos:6 /bin/sh -c "cat /proc/self/maps"

